- name: foodapp on webservers
  hosts: webservers
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: true
    - name: clone github repository
      git:
        repo: https://github.com/saiurakrishna/food-app.git
        dest: /var/www/html
    - name: restart httpd
      service:
        name: httpd
        state: restarted
