- name:setup foodapp on webservers
  hosts: webservers
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: true
    - name: clone github repo for foodapp
      git:
        repo: https://github.com/CHILAKA-UDAYKIRAN/ansible.git
        dest: /var/www/html
        clone: yes
        update: yes 
    - name: restart httpd
      service:
        name: httpd
        state: restarted
